name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create apk path
      run: mkdir -p app/build/outputs/apk/debug
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --info
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/prod/debug/app-prod-debug.apk

  kryptowire_analysis_job:
    needs: [build]
    runs-on: ubuntu-latest
    name: Submit app to Kryptowire Portal
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: apk
          path: path/to/artifact
          
      - name: Kryptowire Analysis Submission
        id: appSubmits
        uses: pkumar001/kryptowire-analysis-action@master
        with:
          path-to-file: path/to/artifact/app-prod-debug.apk
          platform: "android"
          apiKey: "gCkN9ZEevDVY1SqgXxL1lXcPGO7iRHrMomqu"

